# Generated by Django 6.0.6 on 2026-07-03 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('CLEARANCE', 'Barangay Clearance'), ('RESIDENCY', 'Certificate of Residency'), ('INDIGENCY', 'Certificate of Indigency')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('civil_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Legally Separated')], max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
    ]
