# Generated by Django 6.0.6 on 2026-07-07 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('BUSINESS', 'Business Permit'), ('CONSTRUCTION', 'Construction Permit'), ('EVENT', 'Event/Activity Permit'), ('ZONING', 'Zoning Clearance')], max_length=20)),
                ('applicant_name', models.CharField(max_length=255)),
                ('date_needed', models.DateField()),
                ('nature', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('supporting_documents', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
    ]
