# Generated by Django 6.0.6 on 2026-07-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_permitrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitrequest',
            name='purpose',
        ),
    ]
