# Generated by Django 6.0.6 on 2026-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_permitrequest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitrequest',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
