# Generated by Django 6.0.6 on 2026-07-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aiquerystatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Emergency', 'Emergency'), ('Equipment', 'Equipment'), ('Supplies', 'Supplies'), ('Office', 'Office')], max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('For Repair', 'For Repair')], default='Available', max_length=50)),
                ('borrower', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
