# Generated by Django 6.0.6 on 2026-07-13 13:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_announcement_readannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_household', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('member_count', models.IntegerField()),
                ('is_4ps_beneficiary', models.BooleanField(default=False)),
                ('has_senior_citizen', models.BooleanField(default=False)),
                ('has_pwd', models.BooleanField(default=False)),
                ('has_solo_parent', models.BooleanField(default=False)),
                ('housing_status', models.CharField(blank=True, choices=[('Owned', 'Owned'), ('Rented', 'Rented'), ('Informal Settler', 'Informal Settler'), ('Caretaker', 'Caretaker')], max_length=50, null=True)),
                ('dwelling_type', models.CharField(blank=True, choices=[('Concrete', 'Concrete'), ('Semi-Concrete', 'Semi-Concrete'), ('Light Materials', 'Light Materials (Wood/Nipa)')], max_length=50, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
