# Generated by Django 6.0.6 on 2026-07-14 06:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_household'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='household',
            name='has_pwd',
        ),
        migrations.RemoveField(
            model_name='household',
            name='has_senior_citizen',
        ),
        migrations.RemoveField(
            model_name='household',
            name='has_solo_parent',
        ),
        migrations.RemoveField(
            model_name='household',
            name='head_of_household',
        ),
        migrations.RemoveField(
            model_name='household',
            name='is_4ps_beneficiary',
        ),
        migrations.RemoveField(
            model_name='household',
            name='member_count',
        ),
        migrations.AlterField(
            model_name='household',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(default='Single', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('purok', models.CharField(max_length=50)),
                ('relationship_to_head', models.CharField(choices=[('Head', 'Head of Household'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Other', 'Other Relative / Non-Relative')], default='Head', max_length=20)),
                ('is_4ps_beneficiary', models.BooleanField(default=False)),
                ('has_senior_citizen', models.BooleanField(default=False)),
                ('has_pwd', models.BooleanField(default=False)),
                ('has_solo_parent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='api.household')),
            ],
        ),
    ]
