# Generated by Django 6.0.6 on 2026-07-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_household_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
