# Generated by Django 6.0.6 on 2026-07-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_equipment_event_facility_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ACTIVITY', 'Barangay Activity'), ('ABSENCE', 'Official Absence')], default='ACTIVITY', max_length=20),
        ),
    ]
