# Generated by Django 6.0.6 on 2026-07-21 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='facility',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Unavailable', 'Unavailable')], default='Available', max_length=50),
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='official_documents/')),
                ('document_type', models.CharField(choices=[('Ordinance', 'Ordinances (Mga Ordinansa)'), ('Resolution', 'Resolutions (Mga Resolusyon)'), ('EO', 'Executive Orders (EO)'), ('Memo', 'Memorandums'), ('Minutes', 'Meeting Minutes'), ('Financial', 'Financial & Procurement'), ('Template', 'Templates & Forms'), ('Others', 'Others')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
