# Generated by Django 6.0.6 on 2026-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_equipment_status_alter_facility_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocument',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
