# Generated by Django 6.0.6 on 2026-07-23 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userprofile_otp_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_birth_date', models.DateField(blank=True, null=True)),
                ('requested_civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(help_text='Reason for update (e.g., bedridden, PWD)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='api.resident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
