# Generated by Django 6.0.6 on 2026-07-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profileupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdaterequest',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_corrections_ids/'),
        ),
    ]
