# Generated by Django 6.0.6 on 2026-07-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_resident_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcement_media/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='categories',
            field=models.JSONField(default=list, help_text='Stores multiple categories as an array'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Will highlight the announcement in red on the feed'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='linked_event',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this announcement to a specific calendar event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='api.event'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., Water Interruption, Relief)', max_length=255, null=True),
        ),
    ]
