# Generated by Django 6.0.6 on 2026-07-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_announcement_category_announcement_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(default='Barangay Magsaysay', max_length=255)),
                ('captain_name', models.CharField(default='Juan Dela Cruz', max_length=255)),
                ('barangay_hall_address', models.CharField(default='Barangay Hall, Main St.', max_length=255)),
                ('official_contact_email', models.EmailField(default='official@magsaysay.gov.ph', max_length=254)),
                ('official_contact_number', models.CharField(default='09123456789', max_length=50)),
                ('barangay_seal_url', models.CharField(blank=True, max_length=500, null=True)),
                ('emergency_hotline', models.CharField(default='911', max_length=50)),
                ('police_hotline', models.CharField(default='117', max_length=50)),
                ('fire_hotline', models.CharField(default='112', max_length=50)),
                ('ai_chatbot_enabled', models.BooleanField(default=True)),
                ('accept_permit_requests', models.BooleanField(default=True)),
                ('accept_reservations', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('max_pending_requests_per_user', models.IntegerField(default=3)),
                ('reservation_lead_time_days', models.IntegerField(default=2)),
            ],
        ),
    ]
