# Generated by Django 6.0.6 on 2026-07-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_residentapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalresident',
            old_name='has_pwd',
            new_name='is_pwd',
        ),
        migrations.RenameField(
            model_name='historicalresident',
            old_name='has_senior_citizen',
            new_name='is_senior_citizen',
        ),
        migrations.RenameField(
            model_name='historicalresident',
            old_name='has_solo_parent',
            new_name='is_solo_parent',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='has_pwd',
            new_name='is_pwd',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='has_senior_citizen',
            new_name='is_senior_citizen',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='has_solo_parent',
            new_name='is_solo_parent',
        ),
        migrations.RemoveField(
            model_name='historicalresident',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='historicalresident',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='id_picture',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g., Jr., Sr., III', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='residents/ids/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g., Jr., Sr., III', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='residentapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentapplication',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentapplication',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='residentapplication',
            name='civil_status',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='residentapplication',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='residentapplication',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
