# Generated by Django 6.0.6 on 2026-08-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_has_pwd_historicalresident_is_pwd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresident',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='citizenship',
            field=models.CharField(default='Filipino', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='inhabitant_type',
            field=models.CharField(default='NON-MIGRANT', help_text='e.g., NON-MIGRANT, MIGRANT, TRANSIENT', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='mothers_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='mothers_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='mothers_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='citizenship',
            field=models.CharField(default='Filipino', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='inhabitant_type',
            field=models.CharField(default='NON-MIGRANT', help_text='e.g., NON-MIGRANT, MIGRANT, TRANSIENT', max_length=50),
        ),
        migrations.AddField(
            model_name='resident',
            name='mothers_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='mothers_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='mothers_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
