# Generated by Django 6.0.6 on 2026-09-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_historicalresident_birth_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('Barangay', 'Barangay Contacts'), ('Municipal', 'Municipal / City Contacts'), ('National', 'National Hotlines')], default='Barangay', max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
