# Generated by Django 6.0.6 on 2026-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='icon',
            field=models.CharField(default='phone', max_length=50),
        ),
    ]
