# Generated by Django 6.0.6 on 2026-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_emergencycontact_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='role',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('CAPTAIN', 'Captain')], default='RESIDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('CAPTAIN', 'Captain')], default='RESIDENT', max_length=20),
        ),
    ]
