# Generated by Django 6.0.6 on 2026-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_historicaluserprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresident',
            name='is_registered_voter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_registered_voter',
            field=models.BooleanField(default=False),
        ),
    ]
