# Generated by Django 6.0.6 on 2026-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_historicalresident_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresident',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Not in Labor Force', 'Not in Labor Force')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='is_indigenous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='is_ofw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalresident',
            name='is_out_of_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Not in Labor Force', 'Not in Labor Force')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_indigenous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_ofw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_out_of_school',
            field=models.BooleanField(default=False),
        ),
    ]
